"""p3_2_actual_cogs_order_cost_entries

Revision ID: 07038e084fcd
Revises: 82bb321c5322
Create Date: 2026-03-01 21:34:12.550580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07038e084fcd'
down_revision: Union[str, Sequence[str], None] = '82bb321c5322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_cost_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Float(), nullable=False),
    sa.Column('cogs_amount', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'order_item_id', name='uq_order_cost_entry_order_item')
    )
    with op.batch_alter_table('order_cost_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_cost_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_cost_entries_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_cost_entries_id'), ['id'], unique=False)
        batch_op.create_index('ix_order_cost_entries_order_created_at', ['order_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_cost_entries_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_cost_entries_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_cost_entries_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_cost_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_cost_entries_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_cost_entries_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_order_cost_entries_order_id'))
        batch_op.drop_index('ix_order_cost_entries_order_created_at')
        batch_op.drop_index(batch_op.f('ix_order_cost_entries_id'))
        batch_op.drop_index(batch_op.f('ix_order_cost_entries_created_by'))
        batch_op.drop_index(batch_op.f('ix_order_cost_entries_created_at'))

    op.drop_table('order_cost_entries')
    # ### end Alembic commands ###
