"""p2_2_constraints_indexes

Revision ID: 82bb321c5322
Revises: 9851b583f4d7
Create Date: 2026-03-01 20:59:01.528658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bb321c5322'
down_revision: Union[str, Sequence[str], None] = '9851b583f4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_assignments_assigned_at'), ['assigned_at'], unique=False)
        batch_op.create_index('ix_delivery_assignments_driver_status_id', ['driver_id', 'status', 'id'], unique=False)
        batch_op.create_index('ix_delivery_assignments_order_status_id', ['order_id', 'status', 'id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_transactions_created_by'), ['created_by'], unique=False)
        batch_op.create_index('ix_financial_transactions_type_created_at', ['type', 'created_at'], unique=False)
        batch_op.create_index('ux_financial_transactions_expense_expense', ['expense_id'], unique=True, sqlite_where=sa.text("type = 'expense' AND expense_id IS NOT NULL"))
        batch_op.create_index('ux_financial_transactions_refund_order', ['order_id'], unique=True, sqlite_where=sa.text("type = 'refund' AND order_id IS NOT NULL"))
        batch_op.create_index('ux_financial_transactions_sale_order', ['order_id'], unique=True, sqlite_where=sa.text("type = 'sale' AND order_id IS NOT NULL"))

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('order_transitions_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_transitions_log_performed_by'), ['performed_by'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_delivery_team_notified_by'), ['delivery_team_notified_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_paid_by'), ['paid_by'], unique=False)
        batch_op.create_index('ix_orders_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_table_id'), ['table_id'], unique=False)
        batch_op.create_index('ix_orders_table_status_created_at', ['table_id', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('product_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_resources_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_resources_resource_id'), ['resource_id'], unique=False)

    op.execute(
        """
        INSERT INTO product_categories (name, active, sort_order)
        SELECT 'عام', 1, 9999
        WHERE NOT EXISTS (SELECT 1 FROM product_categories WHERE name = 'عام')
        """
    )
    op.execute(
        """
        UPDATE products
        SET category_id = (
            SELECT pc.id
            FROM product_categories pc
            WHERE pc.name = products.category
            LIMIT 1
        )
        WHERE category_id IS NULL
        """
    )
    op.execute(
        """
        UPDATE products
        SET category_id = (SELECT id FROM product_categories WHERE name = 'عام' LIMIT 1)
        WHERE category_id IS NULL
        """
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "category_id",
            existing_type=sa.INTEGER(),
            nullable=False,
        )

    with op.batch_alter_table('resource_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_movements_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('shift_closures', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_shift_closure_business_date', ['business_date'])

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_updated_by'), ['updated_by'], unique=False)

    with op.batch_alter_table('wh_integration_events', schema=None) as batch_op:
        batch_op.create_index('ix_wh_integration_events_status_created_at', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wh_integration_events', schema=None) as batch_op:
        batch_op.drop_index('ix_wh_integration_events_status_created_at')

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_updated_by'))

    with op.batch_alter_table('shift_closures', schema=None) as batch_op:
        batch_op.drop_constraint('uq_shift_closure_business_date', type_='unique')

    with op.batch_alter_table('resource_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_movements_created_by'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('product_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_resources_resource_id'))
        batch_op.drop_index(batch_op.f('ix_product_resources_product_id'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_table_status_created_at')
        batch_op.drop_index(batch_op.f('ix_orders_table_id'))
        batch_op.drop_index('ix_orders_status_created_at')
        batch_op.drop_index(batch_op.f('ix_orders_paid_by'))
        batch_op.drop_index(batch_op.f('ix_orders_delivery_team_notified_by'))

    with op.batch_alter_table('order_transitions_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_transitions_log_performed_by'))

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_created_by'))

    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.drop_index('ux_financial_transactions_sale_order', sqlite_where=sa.text("type = 'sale' AND order_id IS NOT NULL"))
        batch_op.drop_index('ux_financial_transactions_refund_order', sqlite_where=sa.text("type = 'refund' AND order_id IS NOT NULL"))
        batch_op.drop_index('ux_financial_transactions_expense_expense', sqlite_where=sa.text("type = 'expense' AND expense_id IS NOT NULL"))
        batch_op.drop_index('ix_financial_transactions_type_created_at')
        batch_op.drop_index(batch_op.f('ix_financial_transactions_created_by'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_created_by'))

    with op.batch_alter_table('delivery_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_delivery_assignments_order_status_id')
        batch_op.drop_index('ix_delivery_assignments_driver_status_id')
        batch_op.drop_index(batch_op.f('ix_delivery_assignments_assigned_at'))

    # ### end Alembic commands ###
