"""baseline_schema

Revision ID: 9851b583f4d7
Revises:
Create Date: 2026-03-01 20:49:54.651941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9851b583f4d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_cost_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_cost_centers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_cost_centers_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_cost_centers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_expense_cost_centers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_cost_centers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_cost_centers_name'), ['name'], unique=True)

    op.create_table('inventory_warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_warehouses_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_warehouses_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_warehouses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_warehouses_id'), ['id'], unique=False)

    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_categories_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_categories_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_categories_sort_order'), ['sort_order'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('alert_threshold', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_scope'), ['scope'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=True)

    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tables_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_failed_login_at', sa.DateTime(), nullable=True),
    sa.Column('permission_overrides_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_locked_until'), ['locked_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('wh_integration_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wh_integration_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wh_integration_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_integration_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_integration_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_integration_events_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_integration_events_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_integration_events_status'), ['status'], unique=False)

    op.create_table('wh_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('alert_threshold', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wh_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wh_items_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_items_name'), ['name'], unique=True)

    op.create_table('wh_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('payment_term_days', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('quality_rating', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wh_suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wh_suppliers_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_suppliers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_suppliers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_suppliers_name'), ['name'], unique=True)

    op.create_table('delivery_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('vehicle', sa.String(length=120), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_drivers_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_drivers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_drivers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_drivers_user_id'), ['user_id'], unique=True)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['expense_cost_centers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_cost_center_id'), ['cost_center_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_reviewed_by'), ['reviewed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_status'), ['status'], unique=False)

    op.create_table('inventory_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'resource_id', name='uq_inventory_balance')
    )
    with op.batch_alter_table('inventory_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_balances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_balances_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_balances_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_balances_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('balance_before', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('kitchen_resource_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kitchen_resource_id', sa.Integer(), nullable=False),
    sa.Column('stock_resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['kitchen_resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['stock_resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kitchen_resource_id', 'stock_resource_id', name='uq_kitchen_resource_component')
    )
    with op.batch_alter_table('kitchen_resource_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kitchen_resource_components_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kitchen_resource_components_kitchen_resource_id'), ['kitchen_resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kitchen_resource_components_stock_resource_id'), ['stock_resource_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('delivery_fee', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('amount_received', sa.Float(), nullable=True),
    sa.Column('change_amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('delivery_team_notified_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_team_notified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_team_notified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_delivery_team_notified_at'), ['delivery_team_notified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_type'), ['type'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_kind'), ['kind'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('resource_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_movements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_movements_resource_id'), ['resource_id'], unique=False)

    op.create_table('security_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_events_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_events_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_events_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_events_username'), ['username'], unique=False)

    op.create_table('shift_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('opening_cash', sa.Float(), nullable=False),
    sa.Column('sales_total', sa.Float(), nullable=False),
    sa.Column('refunds_total', sa.Float(), nullable=False),
    sa.Column('expenses_total', sa.Float(), nullable=False),
    sa.Column('expected_cash', sa.Float(), nullable=False),
    sa.Column('actual_cash', sa.Float(), nullable=False),
    sa.Column('variance', sa.Float(), nullable=False),
    sa.Column('transactions_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_closures_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_closures_closed_at'), ['closed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_closures_closed_by'), ['closed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_closures_id'), ['id'], unique=False)

    op.create_table('supplier_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_receipts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_receipts_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_receipts_received_by'), ['received_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_receipts_reference_no'), ['reference_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_receipts_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_receipts_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('system_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_audit_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_audit_log_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_audit_log_performed_by'), ['performed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('wh_inbound_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_no', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['wh_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wh_inbound_vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wh_inbound_vouchers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_inbound_vouchers_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_wh_inbound_vouchers_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_inbound_vouchers_received_by'), ['received_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_inbound_vouchers_reference_no'), ['reference_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_inbound_vouchers_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_inbound_vouchers_voucher_no'), ['voucher_no'], unique=True)

    op.create_table('wh_outbound_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_no', sa.String(length=40), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wh_outbound_vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wh_outbound_vouchers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_outbound_vouchers_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_wh_outbound_vouchers_issued_by'), ['issued_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_outbound_vouchers_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_outbound_vouchers_reason_code'), ['reason_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_outbound_vouchers_voucher_no'), ['voucher_no'], unique=True)

    op.create_table('wh_stock_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_unit_cost', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['wh_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', name='uq_wh_stock_balance_item')
    )
    with op.batch_alter_table('wh_stock_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wh_stock_balances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_balances_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_balances_updated_at'), ['updated_at'], unique=False)

    op.create_table('wh_stock_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count_no', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('counted_by', sa.Integer(), nullable=False),
    sa.Column('counted_at', sa.DateTime(), nullable=False),
    sa.Column('settled_by', sa.Integer(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['settled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wh_stock_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wh_stock_counts_count_no'), ['count_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_wh_stock_counts_counted_at'), ['counted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_counts_counted_by'), ['counted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_counts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_counts_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_wh_stock_counts_settled_by'), ['settled_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_counts_status'), ['status'], unique=False)

    op.create_table('wh_stock_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('movement_kind', sa.String(length=24), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('line_value', sa.Float(), nullable=False),
    sa.Column('running_avg_cost', sa.Float(), nullable=False),
    sa.Column('balance_before', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['wh_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wh_stock_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wh_stock_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_ledger_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_ledger_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_ledger_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_ledger_movement_kind'), ['movement_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_ledger_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_ledger_source_type'), ['source_type'], unique=False)

    op.create_table('delivery_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('departed_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['delivery_drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_assignments_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_assignments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_assignments_status'), ['status'], unique=False)

    op.create_table('expense_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=180), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_attachments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_attachments_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_attachments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_attachments_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('financial_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_type'), ['type'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('order_transitions_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=False),
    sa.Column('to_status', sa.String(length=40), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_transitions_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_transitions_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_transitions_log_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_transitions_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('product_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'resource_id', name='uq_product_resource')
    )
    with op.batch_alter_table('product_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_resources_id'), ['id'], unique=False)

    op.create_table('supplier_receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['supplier_receipts.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_receipt_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_receipt_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_receipt_items_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_receipt_items_resource_id'), ['resource_id'], unique=False)

    op.create_table('wh_inbound_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['wh_items.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['wh_inbound_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_id', 'item_id', name='uq_wh_inbound_voucher_item')
    )
    with op.batch_alter_table('wh_inbound_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wh_inbound_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_inbound_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_inbound_items_voucher_id'), ['voucher_id'], unique=False)

    op.create_table('wh_outbound_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['wh_items.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['wh_outbound_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_id', 'item_id', name='uq_wh_outbound_voucher_item')
    )
    with op.batch_alter_table('wh_outbound_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wh_outbound_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_outbound_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_outbound_items_voucher_id'), ['voucher_id'], unique=False)

    op.create_table('wh_stock_count_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('system_quantity', sa.Float(), nullable=False),
    sa.Column('counted_quantity', sa.Float(), nullable=False),
    sa.Column('variance_quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('variance_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['wh_stock_counts.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['wh_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('count_id', 'item_id', name='uq_wh_stock_count_line_item')
    )
    with op.batch_alter_table('wh_stock_count_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wh_stock_count_lines_count_id'), ['count_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_count_lines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_stock_count_lines_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wh_stock_count_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_stock_count_lines_item_id'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_count_lines_id'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_count_lines_count_id'))

    op.drop_table('wh_stock_count_lines')
    with op.batch_alter_table('wh_outbound_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_outbound_items_voucher_id'))
        batch_op.drop_index(batch_op.f('ix_wh_outbound_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_wh_outbound_items_id'))

    op.drop_table('wh_outbound_items')
    with op.batch_alter_table('wh_inbound_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_inbound_items_voucher_id'))
        batch_op.drop_index(batch_op.f('ix_wh_inbound_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_wh_inbound_items_id'))

    op.drop_table('wh_inbound_items')
    with op.batch_alter_table('supplier_receipt_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_receipt_items_resource_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_receipt_items_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_receipt_items_id'))

    op.drop_table('supplier_receipt_items')
    with op.batch_alter_table('product_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_resources_id'))

    op.drop_table('product_resources')
    with op.batch_alter_table('order_transitions_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_transitions_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_order_transitions_log_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_transitions_log_id'))

    op.drop_table('order_transitions_log')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_financial_transactions_order_id'))
        batch_op.drop_index(batch_op.f('ix_financial_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_financial_transactions_expense_id'))
        batch_op.drop_index(batch_op.f('ix_financial_transactions_created_at'))

    op.drop_table('financial_transactions')
    with op.batch_alter_table('expense_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_attachments_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_expense_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_expense_attachments_expense_id'))
        batch_op.drop_index(batch_op.f('ix_expense_attachments_created_at'))

    op.drop_table('expense_attachments')
    with op.batch_alter_table('delivery_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_delivery_assignments_order_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_assignments_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_assignments_driver_id'))

    op.drop_table('delivery_assignments')
    with op.batch_alter_table('wh_stock_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_stock_ledger_source_type'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_ledger_source_id'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_ledger_movement_kind'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_ledger_item_id'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_ledger_id'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_ledger_created_by'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_ledger_created_at'))

    op.drop_table('wh_stock_ledger')
    with op.batch_alter_table('wh_stock_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_stock_counts_status'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_counts_settled_by'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_counts_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_counts_id'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_counts_counted_by'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_counts_counted_at'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_counts_count_no'))

    op.drop_table('wh_stock_counts')
    with op.batch_alter_table('wh_stock_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_stock_balances_updated_at'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_balances_item_id'))
        batch_op.drop_index(batch_op.f('ix_wh_stock_balances_id'))

    op.drop_table('wh_stock_balances')
    with op.batch_alter_table('wh_outbound_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_outbound_vouchers_voucher_no'))
        batch_op.drop_index(batch_op.f('ix_wh_outbound_vouchers_reason_code'))
        batch_op.drop_index(batch_op.f('ix_wh_outbound_vouchers_posted_at'))
        batch_op.drop_index(batch_op.f('ix_wh_outbound_vouchers_issued_by'))
        batch_op.drop_index(batch_op.f('ix_wh_outbound_vouchers_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_wh_outbound_vouchers_id'))

    op.drop_table('wh_outbound_vouchers')
    with op.batch_alter_table('wh_inbound_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_inbound_vouchers_voucher_no'))
        batch_op.drop_index(batch_op.f('ix_wh_inbound_vouchers_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_wh_inbound_vouchers_reference_no'))
        batch_op.drop_index(batch_op.f('ix_wh_inbound_vouchers_received_by'))
        batch_op.drop_index(batch_op.f('ix_wh_inbound_vouchers_posted_at'))
        batch_op.drop_index(batch_op.f('ix_wh_inbound_vouchers_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_wh_inbound_vouchers_id'))

    op.drop_table('wh_inbound_vouchers')
    op.drop_table('system_settings')
    with op.batch_alter_table('system_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_system_audit_log_performed_by'))
        batch_op.drop_index(batch_op.f('ix_system_audit_log_module'))
        batch_op.drop_index(batch_op.f('ix_system_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_system_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_system_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_system_audit_log_action'))

    op.drop_table('system_audit_log')
    with op.batch_alter_table('supplier_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_receipts_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_receipts_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_receipts_reference_no'))
        batch_op.drop_index(batch_op.f('ix_supplier_receipts_received_by'))
        batch_op.drop_index(batch_op.f('ix_supplier_receipts_received_at'))
        batch_op.drop_index(batch_op.f('ix_supplier_receipts_id'))

    op.drop_table('supplier_receipts')
    with op.batch_alter_table('shift_closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_closures_id'))
        batch_op.drop_index(batch_op.f('ix_shift_closures_closed_by'))
        batch_op.drop_index(batch_op.f('ix_shift_closures_closed_at'))
        batch_op.drop_index(batch_op.f('ix_shift_closures_business_date'))

    op.drop_table('shift_closures')
    with op.batch_alter_table('security_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_audit_events_username'))
        batch_op.drop_index(batch_op.f('ix_security_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_audit_events_success'))
        batch_op.drop_index(batch_op.f('ix_security_audit_events_severity'))
        batch_op.drop_index(batch_op.f('ix_security_audit_events_role'))
        batch_op.drop_index(batch_op.f('ix_security_audit_events_ip_address'))
        batch_op.drop_index(batch_op.f('ix_security_audit_events_id'))
        batch_op.drop_index(batch_op.f('ix_security_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_security_audit_events_created_at'))

    op.drop_table('security_audit_events')
    with op.batch_alter_table('resource_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_movements_resource_id'))
        batch_op.drop_index(batch_op.f('ix_resource_movements_id'))
        batch_op.drop_index(batch_op.f('ix_resource_movements_created_at'))

    op.drop_table('resource_movements')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_kind'))
        batch_op.drop_index(batch_op.f('ix_products_is_archived'))
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_type'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_payment_status'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_delivery_team_notified_at'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    with op.batch_alter_table('kitchen_resource_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kitchen_resource_components_stock_resource_id'))
        batch_op.drop_index(batch_op.f('ix_kitchen_resource_components_kitchen_resource_id'))
        batch_op.drop_index(batch_op.f('ix_kitchen_resource_components_id'))

    op.drop_table('kitchen_resource_components')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_source_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_resource_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_created_at'))

    op.drop_table('inventory_movements')
    with op.batch_alter_table('inventory_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_balances_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_balances_updated_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_balances_resource_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_balances_id'))

    op.drop_table('inventory_balances')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_status'))
        batch_op.drop_index(batch_op.f('ix_expenses_reviewed_by'))
        batch_op.drop_index(batch_op.f('ix_expenses_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_expenses_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_created_at'))
        batch_op.drop_index(batch_op.f('ix_expenses_cost_center_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('delivery_drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_drivers_user_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_drivers_status'))
        batch_op.drop_index(batch_op.f('ix_delivery_drivers_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_drivers_active'))

    op.drop_table('delivery_drivers')
    with op.batch_alter_table('wh_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_wh_suppliers_id'))
        batch_op.drop_index(batch_op.f('ix_wh_suppliers_created_at'))
        batch_op.drop_index(batch_op.f('ix_wh_suppliers_active'))

    op.drop_table('wh_suppliers')
    with op.batch_alter_table('wh_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_items_name'))
        batch_op.drop_index(batch_op.f('ix_wh_items_id'))
        batch_op.drop_index(batch_op.f('ix_wh_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_wh_items_active'))

    op.drop_table('wh_items')
    with op.batch_alter_table('wh_integration_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_integration_events_status'))
        batch_op.drop_index(batch_op.f('ix_wh_integration_events_source_type'))
        batch_op.drop_index(batch_op.f('ix_wh_integration_events_source_id'))
        batch_op.drop_index(batch_op.f('ix_wh_integration_events_id'))
        batch_op.drop_index(batch_op.f('ix_wh_integration_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_wh_integration_events_created_at'))

    op.drop_table('wh_integration_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_locked_until'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tables_id'))

    op.drop_table('tables')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))
        batch_op.drop_index(batch_op.f('ix_suppliers_created_at'))
        batch_op.drop_index(batch_op.f('ix_suppliers_active'))

    op.drop_table('suppliers')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_scope'))
        batch_op.drop_index(batch_op.f('ix_resources_id'))
        batch_op.drop_index(batch_op.f('ix_resources_active'))

    op.drop_table('resources')
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_categories_sort_order'))
        batch_op.drop_index(batch_op.f('ix_product_categories_name'))
        batch_op.drop_index(batch_op.f('ix_product_categories_id'))
        batch_op.drop_index(batch_op.f('ix_product_categories_active'))

    op.drop_table('product_categories')
    with op.batch_alter_table('inventory_warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_warehouses_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_warehouses_created_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_warehouses_code'))
        batch_op.drop_index(batch_op.f('ix_inventory_warehouses_active'))

    op.drop_table('inventory_warehouses')
    with op.batch_alter_table('expense_cost_centers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_cost_centers_name'))
        batch_op.drop_index(batch_op.f('ix_expense_cost_centers_id'))
        batch_op.drop_index(batch_op.f('ix_expense_cost_centers_created_at'))
        batch_op.drop_index(batch_op.f('ix_expense_cost_centers_code'))
        batch_op.drop_index(batch_op.f('ix_expense_cost_centers_active'))

    op.drop_table('expense_cost_centers')
    # ### end Alembic commands ###
