"""add delivery_zone_pricing

Revision ID: e60afb356e90
Revises: k0e1f2a3b4c5
Create Date: 2026-04-17 16:47:49.895833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60afb356e90'
down_revision: Union[str, Sequence[str], None] = 'k0e1f2a3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_state')
    with op.batch_alter_table('cashbox_movements', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('direction',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('cash_channel',
               existing_type=sa.VARCHAR(length=24),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('delivery_drivers', schema=None) as batch_op:
        batch_op.alter_column('telegram_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ux_delivery_drivers_user_id'), sqlite_where=sa.text('user_id IS NOT NULL'))

    with op.batch_alter_table('delivery_settlements', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=24),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('driver_share_model',
               existing_type=sa.VARCHAR(length=24),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('driver_share_value',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('expected_customer_total',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('actual_collected_amount',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('food_revenue_amount',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('delivery_revenue_amount',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('driver_due_amount',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('store_due_amount',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('remitted_amount',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('remaining_store_due_amount',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('variance_amount',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('expense_cost_centers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_expense_cost_centers_code'))
        batch_op.drop_index(batch_op.f('ux_expense_cost_centers_name'))

    with op.batch_alter_table('master_tenants', schema=None) as batch_op:
        batch_op.alter_column('paused_addons_json',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('collected_by_channel',
               existing_type=sa.VARCHAR(length=24),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('collection_variance_amount',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_product_categories_name'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_product_categories_name'), ['name'], unique=1)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('collection_variance_amount',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('collected_by_channel',
               existing_type=sa.VARCHAR(length=24),
               server_default=sa.text("'cashier'"),
               existing_nullable=False)

    with op.batch_alter_table('master_tenants', schema=None) as batch_op:
        batch_op.alter_column('paused_addons_json',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)

    with op.batch_alter_table('expense_cost_centers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_expense_cost_centers_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ux_expense_cost_centers_code'), ['code'], unique=1)

    with op.batch_alter_table('delivery_settlements', schema=None) as batch_op:
        batch_op.alter_column('variance_amount',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('remaining_store_due_amount',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('remitted_amount',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('store_due_amount',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('driver_due_amount',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('delivery_revenue_amount',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('food_revenue_amount',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('actual_collected_amount',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('expected_customer_total',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('driver_share_value',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('driver_share_model',
               existing_type=sa.VARCHAR(length=24),
               server_default=sa.text("'full_delivery_fee'"),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=24),
               server_default=sa.text("'pending'"),
               existing_nullable=False)

    with op.batch_alter_table('delivery_drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_delivery_drivers_user_id'), ['user_id'], unique=1, sqlite_where=sa.text('user_id IS NOT NULL'))
        batch_op.alter_column('telegram_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('cashbox_movements', schema=None) as batch_op:
        batch_op.alter_column('cash_channel',
               existing_type=sa.VARCHAR(length=24),
               server_default=sa.text("'cash_drawer'"),
               existing_nullable=False)
        batch_op.alter_column('direction',
               existing_type=sa.VARCHAR(length=8),
               server_default=sa.text("'in'"),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'driver_remittance'"),
               existing_nullable=False)

    op.create_table('subscription_state',
    sa.Column('plan_code', sa.VARCHAR(length=40), nullable=False),
    sa.Column('capabilities_json', sa.TEXT(), nullable=False),
    sa.Column('activated_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('plan_code')
    )
    # ### end Alembic commands ###
